### ISSUE TITLE
No paper in open source

### ISSUE THREAD

**Issue by levBagryansky** [mximp/se-limitations-slr#3]
@mximp I am assigned to review the paper (90) `Enhancing spark's contract checking facilities using symbolic execution` . The article is not in the public domain. 
How to deal with such articles?

**Comment by EugeneDar** [comment]
@mximp, I have a similar problem, I could not find this article in the open sourse (I looked through all the search results).
Mine is (87) `ParSym: Parallel symbolic execution, 2010, International Conference on Software Technology and Engineering (ICSTE)`

**Comment by mximp** [comment]
In this case you will be given another papers for assessment.

**Comment by levBagryansky** [comment]
@mximp ok, thanks
