### ISSUE TITLE
Template typing errors

### ISSUE THREAD

**Issue by advasileva** [mximp/se-limitations-slr#6]
Minor notes on [the template]( https://github.com/mximp/se-limitations-slr/blob/main/study-assesment-round-I-%3CID%3E.md) to fill in:

+ Instead of
```
| 2. Assessment date (`DD.MM.YYY`)              | `???` |
```
should be 
```
| 2. Assessment date (`DD.MM.YYYY`)             | `???` |
```
+ `unnessesary` -> `unnecessary`;
+ Typo in the `presetned` in the 8th section.

**Comment by mximp** [comment]
@advasileva Thanks! Fixed.
