### ISSUE TITLE
Round 1. Comments section

### ISSUE THREAD

**Issue by levBagryansky** [mximp/se-limitations-slr#8]
@mximp 
How can reviewers note that somethings in review goes not as it was conceived?
 For instance, in study there is no "Contribution" section in `(459) CSEFuzz: Fuzz Testing Based on Symbolic Execution`. It has "CONCLUSION AND FUTURE WORK" instead.
Maybe some additional sectoin can help here?

**Comment by mximp** [comment]
@levBagryansky I'm sure I follow your question. Could you please explain what do you mean by "goes not as it was conceived"?

**Comment by levBagryansky** [comment]
@mximp I mean cases when it is impossible to follow the instructions exactly.

**Comment by mximp** [comment]
@levBagryansky I've updated slightly the instructions. The sectioned are mentioned as desired target to search for the information and if missing then the rest of the paper should be considered.
